### ISSUE TITLE
Backward compatibility issue with Qt5 - enterEvent signature change

### ISSUE THREAD

**Issue by otto-link** [BugelNiels/qt-value-slider#18]
There seems to be a backward compatibility issue with Qt5. Signature of `enterEvent` change from `void enterEvent(QEvent *event)` (in Qt5) to `void enterEvent(QEnterEvent *event)` (in Qt6).

Not sure how to do this differently than with a preprocessor directive:
```C++
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    void enterEvent(QEnterEvent *event) override;
#else
    void enterEvent(QEvent *event) override;
#endif
```

If not urgent, I can propose a PR in a week or two.

**Comment by BugelNiels** [comment]
Thanks for noting, I'll see if I can add an additional CI stage that checks against Qt5 for these issues and resolve any issues
